[terminal.shell]
program = "/opt/homebrew/bin/bash"

[font]
size = 15.0

[font.bold]
family = "TX-02"
style = "Bold"

[font.bold_italic]
family = "TX-02"
style = "Bold Italic"

[font.italic]
family = "TX-02"

[font.normal]
family = "TX-02"

[general]
import = ["~/.config/alacritty/colors.toml"]
