tap 'bramstein/webfonttools'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'homebrew/x11'
tap 'koekeishiya/kwm'
tap 'neovim/neovim'
tap 'ravenac95/sudolikeaboss'
brew 'ack'
brew 'openssl'
brew 'pkg-config'
brew 'icu4c'
brew 'readline'
brew 'sqlite'
brew 'aircrack-ng'
brew 'xz'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'pixman'
brew 'cairo'
brew 'git'
brew 'gobject-introspection'
brew 'atk'
brew 'autoconf'
brew 'automake'
brew 'binutils'
brew 'boost'
brew 'cifer'
brew 'cmake'
brew 'gmp'
brew 'coreutils'
brew 'cscope'
brew 'ctags'
brew 'libidn'
brew 'curl'
brew 'dark-mode'
brew 'dex2jar'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'dns2tcp'
brew 'go'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'fcrackzip'
brew 'findutils'
brew 'foremost'
brew 'isl'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gdbm'
brew 'jpeg'
brew 'libtiff'
brew 'shared-mime-info'
brew 'gdk-pixbuf'
brew 'git-flow'
brew 'git-lfs'
brew 'gnu-sed', args: ['with-default-names']
brew 'hicolor-icon-theme'
brew 'jasper'
brew 'harfbuzz'
brew 'pango'
brew 'gtk+'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'gnupg2'
brew 'libtasn1'
brew 'nettle'
brew 'gnutls'
brew 'hashpump'
brew 'htop'
brew 'hub'
brew 'mysql', service_restart: true
brew 'hydra'
brew 'libtool'
brew 'webp'
brew 'imagemagick', args: ['with-webp']
brew 'john'
brew 'knock'
brew 'libdnet'
brew 'libevent'
brew 'libotr'
brew 'python'
brew 'libxml2'
brew 'lua'
brew 'luajit'
brew 'lynx'
brew 'mas'
brew 'mhash'
brew 'mcrypt'
brew 'moreutils'
brew 'netpbm'
brew 'nmap'
brew 'p7zip'
brew 'pidgin'
brew 'pigz'
brew 'pngcheck'
brew 'pv'
brew 'ruby-build'
brew 'rbenv', args: ['HEAD']
brew 're2c'
brew 'reattach-to-user-namespace'
brew 'rename'
brew 'rhino'
brew 's3cmd'
brew 'screenfetch'
brew 'socat'
brew 'spark'
brew 'speedtest_cli'
brew 'sqlmap'
brew 'ssh-copy-id'
brew 'stow'
brew 'tcpflow'
brew 'tcpreplay'
brew 'testssl'
brew 'tmux'
brew 'tree'
brew 'ucspi-tcp'
brew 'unixodbc'
brew 'vbindiff'
brew 'vifm'
brew 'webkit2png'
brew 'wget', args: ['with-iri']
brew 'xhyve', args: ['HEAD']
brew 'youtube-dl'
brew 'zopfli'
brew 'zsh'
brew 'bramstein/webfonttools/sfnt2woff'
brew 'bramstein/webfonttools/sfnt2woff-zopfli'
brew 'bramstein/webfonttools/woff2'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/screen'
brew 'homebrew/dupes/zlib'
brew 'homebrew/php/brew-php-switcher'
brew 'homebrew/x11/openmotif'
brew 'homebrew/x11/xpdf'
brew 'koekeishiya/kwm/kwm'
brew 'neovim/neovim/neovim'
brew 'ravenac95/sudolikeaboss/sudolikeaboss'
cask 'alfred'
cask 'atom'
cask 'battle-net'
cask 'caffeine'
cask 'calibre'
cask 'clamxav'
cask 'discord'
cask 'dropbox'
cask 'firefox'
cask 'gemini'
cask 'gitter'
cask 'google-chrome'
cask 'gpgtools'
cask 'hyperterm'
cask 'istat-menus'
cask 'iterm2'
cask 'ivpn'
cask 'knockknock'
cask 'lastfm'
cask 'little-snitch'
cask 'real-vnc'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'transmission'
cask 'vlc'
cask 'wireshark'
mas 'Evernote (6.9.2)', id: 406056744
mas 'CloudApp (4.1.1)', id: 417602904
mas 'iCleanMemory (1.6)', id: 439277582
mas 'Wallpaper (1.1.0)', id: 885319628
mas 'Monosnap (3.3.0)', id: 540348655
mas 'Twitter (4.2.3)', id: 409789998
mas 'The Unarchiver (3.11.1)', id: 425424353
mas 'ClamXav (2.6.4)', id: 430207028
mas 'Caffeine (1.1.1)', id: 411246225
mas 'Skitch (2.7.8)', id: 425955336
mas '1Password (6.3.3)', id: 443987910
mas 'Rocket.Chat+ (1.3.1)', id: 1086818840
mas 'DaisyDisk (4.2)', id: 411643860
mas 'Transmit (4.4.11)', id: 403388562
mas 'Xcode (8.0)', id: 497799835
mas 'xScope (4.2)', id: 889428659
mas 'Slack (2.0.3)', id: 803453959
mas 'iA Writer (3.2.6)', id: 775737590
mas 'Dash (3.3.1)', id: 449589707
mas 'Sip (4.4.1)', id: 507257563
