tap "bramstein/webfonttools"
tap "getantibody/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
tap "ravenac95/sudolikeaboss"
tap "tavianator/tap"
tap "universal-ctags/universal-ctags"
tap "wagoodman/dive"
cask "xquartz"
brew "openssl"
brew "pcre"
brew "readline"
brew "sqlite"
brew "aircrack-ng"
brew "icu4c"
brew "boost", link: false
brew "gdbm"
brew "lua"
brew "xz"
brew "python"
brew "gettext"
brew "libffi"
brew "atk"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bench"
brew "binutils", link: true
brew "bison"
brew "brew-php-switcher"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "pixman"
brew "chruby"
brew "cifer"
brew "cmake"
brew "composer"
brew "consul"
brew "coreutils"
brew "cowsay"
brew "cscope"
brew "ctags"
brew "curl"
brew "jemalloc"
brew "libevent"
brew "libidn"
brew "dark-mode"
brew "dex2jar"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "dns2tcp"
brew "dnsmasq", restart_service: true
brew "jpeg"
brew "elixir"
brew "exercism"
brew "fcrackzip"
brew "gmp"
brew "libtasn1"
brew "libunistring"
brew "nettle"
brew "p11-kit"
brew "gnutls"
brew "harfbuzz"
brew "lame"
brew "webp"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "figlet"
brew "findutils"
brew "foremost"
brew "libtool"
brew "unixodbc"
brew "fzf"
brew "isl"
brew "mpfr"
brew "gcc"
brew "gdk-pixbuf"
brew "gifski"
brew "git"
brew "git-cal"
brew "git-flow"
brew "gnu-sed", args: ["with-default-names"]
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "go"
brew "pkg-config"
brew "gpg-agent"
brew "grep"
brew "hicolor-icon-theme"
brew "pango"
brew "gtk+"
brew "hashcat"
brew "hashpump"
brew "htop"
brew "httpie"
brew "hub"
brew "hydra"
brew "hyperfine"
brew "shared-mime-info"
brew "imagemagick"
brew "iperf"
brew "ipfs"
brew "jasper"
brew "john"
brew "knock"
brew "kubernetes-cli"
brew "kops"
brew "libdnet"
brew "libotr"
brew "unibilium"
brew "libtermkey"
brew "libusb-compat"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "libxslt"
brew "libyaml"
brew "luajit"
brew "luarocks"
brew "lynx"
brew "mas"
brew "mhash"
brew "mcrypt"
brew "python@2"
brew "mongodb", restart_service: true
brew "moreutils"
brew "msgpack"
brew "mycli"
brew "mysql@5.7", restart_service: true, link: true
brew "neo4j", restart_service: true
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "netpbm"
brew "nginx", restart_service: true
brew "nmap"
brew "opam"
brew "openmotif"
brew "openssh"
brew "openssl@1.1"
brew "p7zip"
brew "peco"
brew "pigz"
brew "pngcheck"
brew "postgresql"
brew "pv"
brew "re2c"
brew "reattach-to-user-namespace"
brew "redis"
brew "rename"
brew "rethinkdb"
brew "rhino"
brew "ripgrep"
brew "ruby-build"
brew "ruby-install"
brew "s3cmd"
brew "screenfetch"
brew "socat"
brew "spark"
brew "speedtest-cli"
brew "sqlmap"
brew "ssh-copy-id"
brew "stow"
brew "tcpflow"
brew "tcpreplay"
brew "terraform"
brew "testssl"
brew "tig", args: ["HEAD"]
brew "tmux"
brew "tree"
brew "ucspi-tcp"
brew "urlview"
brew "utf8proc"
brew "vbindiff"
brew "vifm"
brew "watchman"
brew "webkit2png"
brew "weechat"
brew "wget"
brew "xhyve", args: ["HEAD"]
brew "yarn"
brew "you-get"
brew "youtube-dl"
brew "z"
brew "zeromq"
brew "zlib"
brew "zopfli"
brew "zsh"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "bramstein/webfonttools/woff2"
brew "getantibody/tap/antibody"
brew "heroku/brew/heroku"
brew "ravenac95/sudolikeaboss/sudolikeaboss"
brew "tavianator/tap/bfs"
brew "wagoodman/dive/dive"
cask "1password"
cask "1password-cli"
cask "alacritty"
cask "alfred"
cask "amethyst"
cask "anki"
cask "appcleaner"
cask "battle-net"
cask "beamer"
cask "calibre"
cask "charles"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-hack-nerd-font"
cask "gitter"
cask "google-chrome"
cask "gpg-suite"
cask "graphql-playground"
cask "haskell-platform"
cask "iina"
cask "imageoptim"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "java8"
cask "kap"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keka"
cask "keybase"
cask "knockknock"
cask "launchrocket"
cask "little-snitch"
cask "lumen"
cask "mono-mdk"
cask "monodraw"
cask "numi"
cask "omnidisksweeper"
cask "postico"
cask "postman"
cask "sabnzbd"
cask "sequel-pro"
cask "sequel-pro-nightly"
cask "shuttle"
cask "slack"
cask "sonarr"
cask "spotify"
cask "steam"
cask "telegram"
cask "transmission"
cask "twitch"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "wireshark"
cask "xld"
mas "chat.rocket", id: 1086818840
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.atlassian.trello", id: 1278508951
mas "com.bitdefender.BitdefenderVirusScanner", id: 500154009
mas "com.daisydiskapp.DaisyDisk", id: 411643860
mas "com.fiplab.batteryhealth", id: 490192174
mas "com.iconfactory.mac.xScope", id: 889428659
mas "com.kyome.RunCat", id: 1429033973
mas "com.macpaw.Gemini", id: 463541543
mas "com.monosnap.monosnap", id: 540348655
mas "com.panic.Transmit", id: 403388562
mas "com.reederapp.rkit2.mac", id: 880001334
mas "com.tinyspeck.slackmacgap", id: 803453959
mas "net.shinyfrog.bear", id: 1091189122
mas "pro.writer.mac", id: 775737590
